name: Build for windows
description: Build for Windows
author: Janis Hutz
inputs:
  out:
    description: "The output directory"
    default: ""
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.out }}
branding:
  icon: book
  color: red
